# TCL File Generated by Component Editor 17.0
# Mon Sep 02 15:49:30 COT 2019
# DO NOT MODIFY


# 
# divisor "divisor" v1.0
#  2019.09.02.15:49:30
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module divisor
# 
set_module_property DESCRIPTION ""
set_module_property NAME divisor
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME divisor
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL CLOCK_DIV_50
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file CLOCK_DIV_50.vhd VHDL PATH CLOCK_DIV_50.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLOCK_50MHz
# 
add_interface CLOCK_50MHz clock end
set_interface_property CLOCK_50MHz clockRate 0
set_interface_property CLOCK_50MHz ENABLED true
set_interface_property CLOCK_50MHz EXPORT_OF ""
set_interface_property CLOCK_50MHz PORT_NAME_MAP ""
set_interface_property CLOCK_50MHz CMSIS_SVD_VARIABLES ""
set_interface_property CLOCK_50MHz SVD_ADDRESS_GROUP ""

add_interface_port CLOCK_50MHz CLOCK_50MHz clk Input 1


# 
# connection point CLOCK_100Hz
# 
add_interface CLOCK_100Hz clock start
set_interface_property CLOCK_100Hz associatedDirectClock ""
set_interface_property CLOCK_100Hz clockRate 0
set_interface_property CLOCK_100Hz clockRateKnown false
set_interface_property CLOCK_100Hz ENABLED true
set_interface_property CLOCK_100Hz EXPORT_OF ""
set_interface_property CLOCK_100Hz PORT_NAME_MAP ""
set_interface_property CLOCK_100Hz CMSIS_SVD_VARIABLES ""
set_interface_property CLOCK_100Hz SVD_ADDRESS_GROUP ""

add_interface_port CLOCK_100Hz CLOCK_100Hz clk Output 1


# 
# connection point CLOCK_100KHz
# 
add_interface CLOCK_100KHz clock start
set_interface_property CLOCK_100KHz associatedDirectClock ""
set_interface_property CLOCK_100KHz clockRate 0
set_interface_property CLOCK_100KHz clockRateKnown false
set_interface_property CLOCK_100KHz ENABLED true
set_interface_property CLOCK_100KHz EXPORT_OF ""
set_interface_property CLOCK_100KHz PORT_NAME_MAP ""
set_interface_property CLOCK_100KHz CMSIS_SVD_VARIABLES ""
set_interface_property CLOCK_100KHz SVD_ADDRESS_GROUP ""

add_interface_port CLOCK_100KHz CLOCK_100KHz clk Output 1


# 
# connection point CLOCK_10Hz
# 
add_interface CLOCK_10Hz clock start
set_interface_property CLOCK_10Hz associatedDirectClock ""
set_interface_property CLOCK_10Hz clockRate 0
set_interface_property CLOCK_10Hz clockRateKnown false
set_interface_property CLOCK_10Hz ENABLED true
set_interface_property CLOCK_10Hz EXPORT_OF ""
set_interface_property CLOCK_10Hz PORT_NAME_MAP ""
set_interface_property CLOCK_10Hz CMSIS_SVD_VARIABLES ""
set_interface_property CLOCK_10Hz SVD_ADDRESS_GROUP ""

add_interface_port CLOCK_10Hz CLOCK_10Hz clk Output 1


# 
# connection point CLOCK_10KHz
# 
add_interface CLOCK_10KHz clock start
set_interface_property CLOCK_10KHz associatedDirectClock ""
set_interface_property CLOCK_10KHz clockRate 0
set_interface_property CLOCK_10KHz clockRateKnown false
set_interface_property CLOCK_10KHz ENABLED true
set_interface_property CLOCK_10KHz EXPORT_OF ""
set_interface_property CLOCK_10KHz PORT_NAME_MAP ""
set_interface_property CLOCK_10KHz CMSIS_SVD_VARIABLES ""
set_interface_property CLOCK_10KHz SVD_ADDRESS_GROUP ""

add_interface_port CLOCK_10KHz CLOCK_10KHz clk Output 1


# 
# connection point CLOCK_1Hz
# 
add_interface CLOCK_1Hz clock start
set_interface_property CLOCK_1Hz associatedDirectClock ""
set_interface_property CLOCK_1Hz clockRate 0
set_interface_property CLOCK_1Hz clockRateKnown false
set_interface_property CLOCK_1Hz ENABLED true
set_interface_property CLOCK_1Hz EXPORT_OF ""
set_interface_property CLOCK_1Hz PORT_NAME_MAP ""
set_interface_property CLOCK_1Hz CMSIS_SVD_VARIABLES ""
set_interface_property CLOCK_1Hz SVD_ADDRESS_GROUP ""

add_interface_port CLOCK_1Hz CLOCK_1Hz clk Output 1


# 
# connection point CLOCK_1KHz
# 
add_interface CLOCK_1KHz clock start
set_interface_property CLOCK_1KHz associatedDirectClock ""
set_interface_property CLOCK_1KHz clockRate 0
set_interface_property CLOCK_1KHz clockRateKnown false
set_interface_property CLOCK_1KHz ENABLED true
set_interface_property CLOCK_1KHz EXPORT_OF ""
set_interface_property CLOCK_1KHz PORT_NAME_MAP ""
set_interface_property CLOCK_1KHz CMSIS_SVD_VARIABLES ""
set_interface_property CLOCK_1KHz SVD_ADDRESS_GROUP ""

add_interface_port CLOCK_1KHz CLOCK_1KHz clk Output 1


# 
# connection point CLOCK_1MHz
# 
add_interface CLOCK_1MHz clock start
set_interface_property CLOCK_1MHz associatedDirectClock ""
set_interface_property CLOCK_1MHz clockRate 0
set_interface_property CLOCK_1MHz clockRateKnown false
set_interface_property CLOCK_1MHz ENABLED true
set_interface_property CLOCK_1MHz EXPORT_OF ""
set_interface_property CLOCK_1MHz PORT_NAME_MAP ""
set_interface_property CLOCK_1MHz CMSIS_SVD_VARIABLES ""
set_interface_property CLOCK_1MHz SVD_ADDRESS_GROUP ""

add_interface_port CLOCK_1MHz CLOCK_1MHz clk Output 1

