# TCL File Generated by Component Editor 16.1
# Tue Apr 18 13:45:38 CST 2017
# DO NOT MODIFY


# 
# TERASIC_ALSA "TERASIC_ALSA" v1.0
#  2017.04.18.13:45:38
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module TERASIC_ALSA
# 
set_module_property DESCRIPTION ""
set_module_property NAME TERASIC_ALSA
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Terasic/
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME TERASIC_ALSA
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL TERASIC_ALSA
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file TERASIC_ALSA.v VERILOG PATH TERASIC_ALSA.v TOP_LEVEL_FILE
add_fileset_file capture_fifo.v VERILOG PATH capture_fifo.v
add_fileset_file i2s_clkctrl_apb.v VERILOG PATH i2s_clkctrl_apb.v
add_fileset_file i2s_output_apb.v VERILOG PATH i2s_output_apb.v
add_fileset_file i2s_shift_in.v VERILOG PATH i2s_shift_in.v
add_fileset_file i2s_shift_out.v VERILOG PATH i2s_shift_out.v
add_fileset_file playback_fifo.v VERILOG PATH playback_fifo.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point chip_conduit_end
# 
add_interface chip_conduit_end conduit end
set_interface_property chip_conduit_end associatedClock clock
set_interface_property chip_conduit_end associatedReset reset
set_interface_property chip_conduit_end ENABLED true
set_interface_property chip_conduit_end EXPORT_OF ""
set_interface_property chip_conduit_end PORT_NAME_MAP ""
set_interface_property chip_conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property chip_conduit_end SVD_ADDRESS_GROUP ""

add_interface_port chip_conduit_end AUD_XCK xck Output 1
add_interface_port chip_conduit_end AUD_ADCLRCK adclrck Bidir 1
add_interface_port chip_conduit_end AUD_ADCDAT adcdat Input 1
add_interface_port chip_conduit_end AUD_BCLK bclk Bidir 1
add_interface_port chip_conduit_end AUD_DACDAT dacdat Output 1
add_interface_port chip_conduit_end AUD_DACLRCK daclrck Bidir 1


# 
# connection point apb_slave_output
# 
add_interface apb_slave_output apb end
set_interface_property apb_slave_output associatedClock clock
set_interface_property apb_slave_output associatedReset reset
set_interface_property apb_slave_output ENABLED true
set_interface_property apb_slave_output EXPORT_OF ""
set_interface_property apb_slave_output PORT_NAME_MAP ""
set_interface_property apb_slave_output CMSIS_SVD_VARIABLES ""
set_interface_property apb_slave_output SVD_ADDRESS_GROUP ""

add_interface_port apb_slave_output output_paddr paddr Input 5
add_interface_port apb_slave_output output_penable penable Input 1
add_interface_port apb_slave_output output_prdata prdata Output 32
add_interface_port apb_slave_output output_pready pready Output 1
add_interface_port apb_slave_output output_psel psel Input 1
add_interface_port apb_slave_output output_pwdata pwdata Input 32
add_interface_port apb_slave_output output_pwrite pwrite Input 1


# 
# connection point apb_slave_clkctrl
# 
add_interface apb_slave_clkctrl apb end
set_interface_property apb_slave_clkctrl associatedClock clock
set_interface_property apb_slave_clkctrl associatedReset reset
set_interface_property apb_slave_clkctrl ENABLED true
set_interface_property apb_slave_clkctrl EXPORT_OF ""
set_interface_property apb_slave_clkctrl PORT_NAME_MAP ""
set_interface_property apb_slave_clkctrl CMSIS_SVD_VARIABLES ""
set_interface_property apb_slave_clkctrl SVD_ADDRESS_GROUP ""

add_interface_port apb_slave_clkctrl clkctrl_paddr paddr Input 5
add_interface_port apb_slave_clkctrl clkctrl_penable penable Input 1
add_interface_port apb_slave_clkctrl clkctrl_prdata prdata Output 32
add_interface_port apb_slave_clkctrl clkctrl_pready pready Output 1
add_interface_port apb_slave_clkctrl clkctrl_psel psel Input 1
add_interface_port apb_slave_clkctrl clkctrl_pwdata pwdata Input 32
add_interface_port apb_slave_clkctrl clkctrl_pwrite pwrite Input 1


# 
# connection point dma_conduit_end
# 
add_interface dma_conduit_end conduit end
set_interface_property dma_conduit_end associatedClock clock
set_interface_property dma_conduit_end associatedReset reset
set_interface_property dma_conduit_end ENABLED true
set_interface_property dma_conduit_end EXPORT_OF ""
set_interface_property dma_conduit_end PORT_NAME_MAP ""
set_interface_property dma_conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property dma_conduit_end SVD_ADDRESS_GROUP ""

add_interface_port dma_conduit_end capture_dma_ack capture_dma_ack Input 1
add_interface_port dma_conduit_end capture_dma_req capture_dma_req Output 1
add_interface_port dma_conduit_end playback_dma_ack playback_dma_ack Input 1
add_interface_port dma_conduit_end playback_dma_req playback_dma_req Output 1


# 
# connection point clock_sink_44
# 
add_interface clock_sink_44 clock end
set_interface_property clock_sink_44 clockRate 0
set_interface_property clock_sink_44 ENABLED true
set_interface_property clock_sink_44 EXPORT_OF ""
set_interface_property clock_sink_44 PORT_NAME_MAP ""
set_interface_property clock_sink_44 CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink_44 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_44 clk_44 clk Input 1


# 
# connection point clock_sink_48
# 
add_interface clock_sink_48 clock end
set_interface_property clock_sink_48 clockRate 0
set_interface_property clock_sink_48 ENABLED true
set_interface_property clock_sink_48 EXPORT_OF ""
set_interface_property clock_sink_48 PORT_NAME_MAP ""
set_interface_property clock_sink_48 CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink_48 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_48 clk_48 clk Input 1

