# TCL File Generated by Component Editor 16.1
# Fri Feb 03 12:00:28 CST 2017
# DO NOT MODIFY


# 
# TERASIC_SEG7 "TERASIC_SEG7" v1.0
#  2017.02.03.12:00:28
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module TERASIC_SEG7
# 
set_module_property DESCRIPTION ""
set_module_property NAME TERASIC_SEG7
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Terasic/
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME TERASIC_SEG7
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL TERASIC_SEG7
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file TERASIC_SEG7.v VERILOG PATH TERASIC_SEG7.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter SEG7_NUM INTEGER 8
set_parameter_property SEG7_NUM DEFAULT_VALUE 8
set_parameter_property SEG7_NUM DISPLAY_NAME SEG7_NUM
set_parameter_property SEG7_NUM TYPE INTEGER
set_parameter_property SEG7_NUM UNITS None
set_parameter_property SEG7_NUM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SEG7_NUM HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 3
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 3
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter DEFAULT_ACTIVE INTEGER 1
set_parameter_property DEFAULT_ACTIVE DEFAULT_VALUE 1
set_parameter_property DEFAULT_ACTIVE DISPLAY_NAME DEFAULT_ACTIVE
set_parameter_property DEFAULT_ACTIVE TYPE INTEGER
set_parameter_property DEFAULT_ACTIVE UNITS None
set_parameter_property DEFAULT_ACTIVE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DEFAULT_ACTIVE HDL_PARAMETER true
add_parameter LOW_ACTIVE INTEGER 1
set_parameter_property LOW_ACTIVE DEFAULT_VALUE 1
set_parameter_property LOW_ACTIVE DISPLAY_NAME LOW_ACTIVE
set_parameter_property LOW_ACTIVE TYPE INTEGER
set_parameter_property LOW_ACTIVE UNITS None
set_parameter_property LOW_ACTIVE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LOW_ACTIVE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end SEG7 writedata Output SEG7_NUM*8


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink s_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink s_reset reset Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock_sink
set_interface_property slave associatedReset reset_sink
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave s_address address Input ADDR_WIDTH
add_interface_port slave s_read read Input 1
add_interface_port slave s_readdata readdata Output 32
add_interface_port slave s_write write Input 1
add_interface_port slave s_writedata writedata Input 32
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0

